### ISSUE TITLE
{{resourceName}} alias should not be just the last segment of the Azure Resource ID

### ISSUE THREAD

**Issue by asheniam** [grafana/azure-monitor-datasource#30]
The calculation of the {{resourceName}} alias should not be just the last segment of the Azure Resource ID.  It should be the concatenation of every odd segment after providers/{providerName}.

For example, an Azure Resource ID will look as follows:

/subscriptions/{subscriptionId}/resourcegroups/{resourceGroup}/providers/{providrrName}/{type1}/{name1}/{type2}/{name2}/...

The {resourceName} alias should be set to {name1}/{name2}/...

An example which illustrates this problem is metrics on Microsoft.storage/storageaccounts/blobservices.  If you have multiple storage accounts, the {resourceName} alias will always be 'default' and you can't tell which storage account is which one.

If the Azure Resource ID is the following:

/subscriptions/{subscriptionId}/resourcegroups/{resourcegroup}/providers/microsoft.storage/storageaccounts/{storageaccountname}/blobservices/default

The {resourceName} alias should be {storageaccountname}/default

**Comment by daniellee** [comment]
This repo is going to be archived. The Azure Monitor plugin was moved into the Grafana repository for version 6.0 of Grafana. If you are using Grafana 6.x then you will automatically start using the built-in version of the Azure Monitor datasource.

Announcement: https://grafana.com/blog/2019/02/25/grafana-v6.0-released/#azure-monitor-datasource
Documentation for Azure Monitor in Grafana: https://grafana.com/docs/features/datasources/azuremonitor/

This issue is ported to the Grafana repo: https://github.com/grafana/grafana/issues/17222
