### ISSUE TITLE
Autocomplete not finding resource type 'Microsoft.DocumentDB/databaseAccount'

### ISSUE THREAD

**Issue by thelious1974** [grafana/azure-monitor-datasource#35]
Hi,

We're currently using the data source to connect to graph quite a few of our resources in Azure using Azure Monitor.

We're trying to select a resource of type 'Microsoft.DocumentDB/databaseAccount', but it's not available in the drop down list after we select the resource group we're interested in.

I've verified that the resource is in the correct subscription/resource group and even used Powershell to get the Azure Monitor metrics from it.

![no_document_db_type](https://user-images.githubusercontent.com/36482610/36252976-315d5834-123e-11e8-9030-63f4781aed4c.png)

Attached is a screenshot showing this.

In chrome's debug window, the call to `api/datasources/proxy/14/azuremonitor/subscriptions/<SUB>/resourceGroups/<RESOURCE GROUP>/resources?api-version=2017-06-01`  does contain the resource of type Microsoft.DocumentDb/databaseAccounts

I've had a look through the source, and I'm afraid my typescript isn't up to the task of tracking down the bug, so I thought I'd report it instead.

Regards,

Mark.

**Comment by thelious1974** [comment]
I forgot to mention,  we're running 0.0.9 of the plugin on Grafana version 4.6.2

**Comment by daniellee** [comment]
This is what it looks like for me:

![image](https://user-images.githubusercontent.com/434655/37140605-9c178e86-22b2-11e8-9d83-7a0752331eba.png)

I will see if I can figure out why it is not showing up for you.

**Comment by yesoreyeram** [comment]
We are also having this issues. When i inspected the network, JSON response does have the value "Microsoft.DocumentDb/databaseAccounts". We have tested in 4.5.2 and 5.0.1 with plugin version 0.0.9.

![image](https://user-images.githubusercontent.com/153843/37341055-0d866656-26b8-11e8-90b6-245952219135.png)

**Comment by thelious1974** [comment]
In fact,  I just tried it on our prod grafana instance, which is still running 4.5.2.. and it now works.
Everything equal, i wonder if MS accidentally broke something then fixed it?

**Comment by yesoreyeram** [comment]
@thelious1974  if that is the case ( MS fixed ) why it is not working with 5.0.1 ? Have you tried with 5.0.1?

**Comment by thelious1974** [comment]
@yesoreyeram If that's the case,  I'll re-open, but it's now working in an environment where it wasn't before.... (ie:  grafana 4.5.2 with version 0.0.9 of the plugin).

I haven't tried with 5.0.1, but considering it cleared up for me in our prod environment (which used to fail), it has to be something MS side..

**Comment by yesoreyeram** [comment]
I have tried with 4.5.2, 5.0.1 and 5.0.2 . Still no luck.

**Comment by yesoreyeram** [comment]
With a little debugging, here is some more information about where the data is getting filtered.
In getMetricDefinitions method from [azure_monitor_datasource.ts](https://github.com/grafana/azure-monitor-datasource/blob/5dd6d8cbdf46b0304b9d2d1bbf35f7eefe86abc1/src/azure_monitor/azure_monitor_datasource.ts) and function call is 

`_.startsWith(t.value, this.supportedMetricNamespaces[i])`

This is due to case issue where as ['Microsoft.DocumentDb'](https://github.com/grafana/azure-monitor-datasource/blob/5dd6d8cbdf46b0304b9d2d1bbf35f7eefe86abc1/src/azure_monitor/supported_namespaces.ts#L12), checks against orignial response'Microsoft.DocumentDB',

Grafana version : 5.0.1
Azure monitor plugin version : 0.0.9

some debug snapshots:

![image](https://user-images.githubusercontent.com/153843/37523007-9890070e-291d-11e8-8053-790b0607f517.png)

![image](https://user-images.githubusercontent.com/153843/37523024-a25a4fce-291d-11e8-8aab-a321d1e3c4cd.png)

I have submitted a pull request https://github.com/grafana/azure-monitor-datasource/pull/39 for this issue.

**Comment by yesoreyeram** [comment]
Network response from azure

![image](https://user-images.githubusercontent.com/153843/37524247-314d4aee-2921-11e8-88bc-8492f7e3ec09.png)

**Comment by yesoreyeram** [comment]
@thelious1974, I wonder how this worked for you in 5.0.2. Could you check the case of the response and confirm? 

I tested the https://github.com/grafana/azure-monitor-datasource/pull/40 and it is working fine. Now i am able  to get metrics for CosmosDB(b)

**Comment by thelious1974** [comment]
This will be because my network response from Azure is coming back as:

![image](https://user-images.githubusercontent.com/36482610/37532298-8c8e742c-2936-11e8-8b98-5aa568b9df5b.png)

**Comment by daniellee** [comment]
The 0.1.0 release is out now and I think this issue is fixed by #40. But I'm not sure as I cannot recreate this.

@thelious1974 could you test if your issue is resolved when you update to 0.1.0. Thanks!

**Comment by thelious1974** [comment]
This is behaving as expected now - I'm seeing results for both `Microsoft.DocumentDB/databaseAccounts` and `Microsoft.DocumentDb/databaseAccounts` in the Namespace field within grafana when using the data source.

I tested with 0.1.1, freshly updated this morning.

@daniellee  Thanks for helping move this forward and @yesoreyeram  Thanks for fixing!
